import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { readSessionUser } from "../../lib/session";
import { errorText, utilityApi, utilityKey, type Page } from "./api";
import { UtilityHero } from "./UtilityHero";
import { useUtilitySummary } from "./useUtilitySummary";
import "./utilities.css";

type Post = { id: string; title: string; content: string; author: string; mine: boolean; category: string;
  modality: string; education_level: string; curricular_area: string; context: string; useful_count: number; useful: boolean; saved: boolean };
const categories: Record<string, string> = { experiencia: "Experiencia", pregunta: "Pregunta", recurso: "Recurso", idea: "Idea" };

export function CommunityPage() {
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [page, setPage] = useState(1);
  const [q, setQ] = useState("");
  const [category, setCategory] = useState("");
  const [saved, setSaved] = useState(false);
  const [open, setOpen] = useState<string | null>(null);
  const [editing, setEditing] = useState<Post | null>(null);
  const [pendingDelete, setPendingDelete] = useState<Post | null>(null);
  const client = useQueryClient();
  const summary = useUtilitySummary();
  const query = useQuery({ queryKey: utilityKey("community", page, q, category, saved), queryFn: ({ signal }) => utilityApi<Page<Post>>(`/community/feed?page=${page}&q=${encodeURIComponent(q)}&category=${category}&saved=${saved}`, "GET", undefined, signal) });
  const mutation = useMutation({ mutationFn: ({ path, method, body }: { path: string; method: string; body?: unknown }) => utilityApi(path, method, body), onSuccess: () => client.invalidateQueries({ queryKey: utilityKey("community") }) });
  return <main className="content-page utilities-page"><UtilityHero eyebrow="COMUNIDAD DOCENTE" title="Comunidad activa" description="Comparte experiencias, encuentra respuestas y guarda aportes útiles para tu aula." metrics={[
    { label: "aportes publicados", value: summary.data?.community?.posts ?? "—" },
    { label: "aportes guardados", value: summary.data?.community?.saved ?? "—" },
  ]}><p className="utility-hero__hint">Comparte prácticas sin incluir datos identificables de estudiantes. Los aportes se pueden guardar, comentar y moderar.</p></UtilityHero>
    <form className="utility-panel utilities-form" key={editing?.id ?? "new"} onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; try { await mutation.mutateAsync({ path: editing ? `/community/posts/${editing.id}` : "/community/posts", method: editing ? "PATCH" : "POST", body: { ...Object.fromEntries(new FormData(form)), ...(editing ? {} : { request_id: requestId }) } }); setEditing(null); setRequestId(crypto.randomUUID()); form.reset(); } catch { /* Preserve text for retry. */ } }}>
      <h2>{editing ? "Editar aporte" : "Comparte con otros docentes"}</h2><p>Tu publicación será visible para los docentes de Avendia. Evita nombres, notas y datos personales de estudiantes.</p><label>Título<input name="title" minLength={4} maxLength={180} required defaultValue={editing?.title} placeholder="Ej. Una dinámica de lectura para aulas multigrado" /></label><label>Contenido<textarea name="content" minLength={12} maxLength={6000} required rows={4} defaultValue={editing?.content} placeholder="Describe el contexto, los pasos y qué funcionó. Si tienes una pregunta, explica qué necesitas resolver." /></label>
      <div className="utilities-grid"><label>Categoría<select name="category" defaultValue={editing?.category}>{Object.entries(categories).map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select></label><label>Modalidad<select name="modality" defaultValue={editing?.modality ?? readSessionUser().education_modality}><option>EBR</option><option>EBA</option><option>EBE</option></select></label><label>Nivel<input name="education_level" minLength={2} maxLength={32} required defaultValue={editing?.education_level ?? readSessionUser().education_level} /></label><label>Área curricular<input name="curricular_area" minLength={2} maxLength={120} required defaultValue={editing?.curricular_area ?? readSessionUser().curricular_area} /></label><label>Contexto<select name="context" defaultValue={editing?.context}><option value="urbano">Urbano</option><option value="rural">Rural</option><option value="rural_multigrado">Rural multigrado</option></select></label></div><div className="utilities-actions"><button className="primary-button" disabled={mutation.isPending}>{editing ? "Guardar cambios" : "Publicar aporte"}</button>{editing ? <button className="secondary-button" type="button" onClick={() => setEditing(null)}>Cancelar</button> : null}</div>
    </form>{mutation.isError ? <p role="alert">{errorText(mutation.error)}</p> : null}
    <section className="utility-panel"><div className="utilities-filters"><label>Buscar<input value={q} onChange={e => { setQ(e.target.value); setPage(1); }} /></label><label>Categoría<select value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">Todas</option>{Object.entries(categories).map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select></label><label className="utilities-check"><input type="checkbox" checked={saved} onChange={e => { setSaved(e.target.checked); setPage(1); }} />Solo mis guardados</label></div>
      {query.isPending ? <p>Cargando aportes…</p> : query.isError ? <p role="alert">{errorText(query.error)} <button onClick={() => void query.refetch()}>Reintentar</button></p> : <>{query.data.items.length === 0 ? <p>No hay aportes con estos filtros. Comparte una experiencia o una pregunta.</p> : query.data.items.map(p => <article className="utilities-card" key={p.id}><small>{p.author} · {p.modality} · {p.education_level} · {categories[p.category]}</small><h2>{p.title}</h2><p className="utilities-prose">{p.content}</p><div className="utilities-actions"><button className="secondary-button" disabled={mutation.isPending} aria-pressed={p.useful} onClick={() => mutation.mutate({ path: `/community/posts/${p.id}/reactions/useful?enabled=${!p.useful}`, method: "PUT" })}>{p.useful ? "Retirar útil" : "Útil"} · {p.useful_count}</button><button className="secondary-button" disabled={mutation.isPending} aria-pressed={p.saved} onClick={() => mutation.mutate({ path: `/community/posts/${p.id}/reactions/saved?enabled=${!p.saved}`, method: "PUT" })}>{p.saved ? "Quitar guardado" : "Guardar"}</button><button className="secondary-button" aria-expanded={open === p.id} onClick={() => setOpen(open === p.id ? null : p.id)}>Comentarios</button>{p.mine ? <><button className="secondary-button" onClick={() => { setEditing(p); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Editar</button><button className="secondary-button" onClick={() => setPendingDelete(p)}>Retirar publicación</button></> : null}</div>
        {readSessionUser().role === "admin" ? <form className="utilities-form" onSubmit={e => { e.preventDefault(); mutation.mutate({ path: `/admin/community/${p.id}`, method: "PATCH", body: { status: "hidden", reason: new FormData(e.currentTarget).get("reason") } }); }}><label>Motivo de moderación<input name="reason" required minLength={4} maxLength={500} placeholder="Explica por qué se retira este aporte" /></label><button className="secondary-button" disabled={mutation.isPending}>Ocultar con registro de auditoría</button></form> : null}
        {open === p.id ? <CommunityComments id={p.id} /> : null}</article>)}<div className="utilities-actions"><button className="secondary-button" disabled={page === 1} onClick={() => setPage(p => p-1)}>Anterior</button><span>Página {page}</span><button className="secondary-button" disabled={page*12 >= query.data.total} onClick={() => setPage(p => p+1)}>Siguiente</button></div></>}
    </section>{pendingDelete ? <div className="dialog-backdrop"><section className="history-confirm" role="dialog" aria-modal="true" aria-label="Retirar publicación"><h2>¿Retirar «{pendingDelete.title}»?</h2><p>Dejará de ser visible para la comunidad. El registro se conservará para moderación.</p><div className="utilities-actions"><button className="secondary-button" onClick={() => setPendingDelete(null)}>Cancelar</button><button className="primary-button" disabled={mutation.isPending} onClick={async () => { try { await mutation.mutateAsync({ path: `/community/posts/${pendingDelete.id}`, method: "DELETE" }); setPendingDelete(null); } catch { /* Show mutation error. */ } }}>Retirar</button></div>{mutation.isError ? <p role="alert">{errorText(mutation.error)}</p> : null}</section></div> : null}
  </main>;
}

function CommunityComments({ id }: { id: string }) {
  const [page, setPage] = useState(1);
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const client = useQueryClient();
  const query = useQuery({ queryKey: utilityKey("community-comments", id, page), queryFn: ({ signal }) => utilityApi<Page<{ id: string; author: string; content: string }>>(`/community/posts/${id}/comments?page=${page}`, "GET", undefined, signal) });
  const mutation = useMutation({ mutationFn: (content: string) => utilityApi(`/community/posts/${id}/comments`, "POST", { content, request_id: requestId }), onSuccess: () => client.invalidateQueries({ queryKey: utilityKey("community-comments", id) }) });
  return <div>{query.isPending ? <p>Cargando…</p> : query.isError ? <p role="alert">{errorText(query.error)}</p> : <>{query.data.items.map(c => <blockquote key={c.id}><strong>{c.author}</strong><p className="utilities-prose">{c.content}</p></blockquote>)}<div className="utilities-actions"><button disabled={page === 1} onClick={() => setPage(p => p-1)}>Anterior</button><button disabled={page*20 >= query.data.total} onClick={() => setPage(p => p+1)}>Más comentarios</button></div></>}
    <form className="utilities-form" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; try { await mutation.mutateAsync(String(new FormData(form).get("content"))); form.reset(); setRequestId(crypto.randomUUID()); } catch { /* Keep draft. */ } }}><label>Tu respuesta<textarea name="content" required minLength={2} maxLength={3000} /></label><button className="secondary-button" disabled={mutation.isPending}>Enviar respuesta</button></form>{mutation.isError ? <p role="alert">{errorText(mutation.error)}</p> : null}</div>;
}
