import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { errorText, utilityApi, utilityKey } from "./api";
import "./utilities.css";

type Analysis = { warnings?: string[]; fields?: string[]; size_bytes?: number; sha256?: string };
type Details = { name: string; category: string; description: string; tags: string[]; analysis: Analysis };
export function TemplateDetails({ id, refresh }: { id: string; refresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const query = useQuery({ queryKey: utilityKey("template-details", id), enabled: open, queryFn: ({ signal }) => utilityApi<Details>(`/templates/${id}/details`, "GET", undefined, signal) });
  const mutation = useMutation({ mutationFn: ({ analyze = false, body }: { analyze?: boolean; body?: unknown }) => utilityApi(`/templates/${id}/${analyze ? "analyze" : "details"}`, analyze ? "POST" : "PUT", body), onSuccess: async () => { await query.refetch(); await refresh(); } });
  return <div className="utilities-page" style={{ gridColumn: "1 / -1", width: "100%" }}><button className="secondary-button" aria-expanded={open} onClick={() => setOpen(!open)}>Clasificar y analizar</button>{open ? <div>{query.isPending ? <p>Cargando información…</p> : query.isError ? <p role="alert">{errorText(query.error)}</p> : query.data ? <><form className="utilities-form" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); mutation.mutate({ body: { name: form.get("name"), category: form.get("category"), description: form.get("description"), tags: String(form.get("tags")).split(",").map(v => v.trim()).filter(Boolean) } }); }}><label>Nombre<input name="name" defaultValue={query.data.name} required minLength={3} maxLength={240} /></label><label>Categoría<select name="category" defaultValue={query.data.category}>{["sesion", "unidad", "pca", "rubrica", "lista-cotejo", "ficha", "informe", "tutoria", "inclusion", "otros"].map(c => <option key={c}>{c}</option>)}</select></label><label>Descripción<textarea name="description" maxLength={2000} defaultValue={query.data.description} /></label><label>Etiquetas (separadas por coma)<input name="tags" defaultValue={query.data.tags.join(", ")} /></label><button className="secondary-button" disabled={mutation.isPending}>Guardar clasificación</button></form><button className="secondary-button" disabled={mutation.isPending} onClick={() => mutation.mutate({ analyze: true })}>{mutation.isPending ? "Procesando…" : "Analizar estructura del archivo"}</button>{query.data.analysis.sha256 ? <div><h3>Informe privado del formato</h3><p>Marcadores detectados: {query.data.analysis.fields?.join(", ") || "Ninguno"}</p>{query.data.analysis.warnings?.map((warning, index) => <p key={index}>{warning}</p>)}</div> : null}</> : null}{mutation.isError ? <p role="alert">{errorText(mutation.error)}</p> : null}</div> : null}</div>;
}
