"""user subscriptions and phone

Revision ID: c7f0686049e8
Revises: 0009_community_posts
Create Date: 2026-09-03 11:57:28.020800
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c7f0686049e8"
down_revision: str | None = "0009_community_posts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=32), nullable=True))
    op.add_column(
        "users", sa.Column("subscription_start", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("subscription_end", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("created_by_admin", sa.String(length=160), nullable=True)
    )
    op.add_column(
        "users", sa.Column("updated_by_admin", sa.String(length=160), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_by_admin")
    op.drop_column("users", "created_by_admin")
    op.drop_column("users", "subscription_end")
    op.drop_column("users", "subscription_start")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
